version: 0.0
os: linux

# Define the source and destination for your deployment files
files:
  - source: /
    destination: /var/www/html/wordpress/

# Hooks to define actions during the deployment lifecycle
hooks:
  # Uncomment and adjust these lines if you need pre-install steps
  # BeforeInstall:
  #   - location: scripts/cleanup.sh      # Optional: Add a cleanup step if needed before the install
  #     runas: root

  ApplicationStart:
    - location: scripts/start_apache.sh # Script to start Apache after deployment
      timeout: 300
      runas: root
